# Generated by Django 3.0 on 2020-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuicideStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=6)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('suicide_no', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
