# Generated by Django 3.0 on 2020-11-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suicidestat',
            old_name='suicide_no',
            new_name='suicides_no',
        ),
    ]
