# Generated by Django 3.0 on 2020-11-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201118_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suicidestat',
            name='suicides_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
