# Generated by Django 3.0 on 2020-11-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201118_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suicidestat',
            name='population',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
